### ISSUE TITLE
支付宝屡次停止运行

### ISSUE THREAD

**Issue by wjcwqc** [WithHades/forestHook#11]
机型：Mi6
系统：MIUI国际版9.6.27开发板
root：magisk
框架：Edxposed
问题：ed中勾选框架后重启或软重启支付宝均无法正常运行，也无法查看错误日志。
建议：可以搞个夏普的实体机（淘宝一百块）完整root系统不要用虚拟化root，测试框架

**Comment by WithHades** [comment]
edxposed没有进行测试，没有了解过这个框架。
你可以下载插件源码，再插件源码内部打印日志查看问题原因。
我这边测试采用的真机为乐视1S，在小米note2上，采用virtualxposed也测试通过.
所以会不会是edxposed与插件源码部分不相容导致的错误？

**Comment by WithHades** [comment]
> 机型：Mi6
> 系统：MIUI国际版9.6.27开发板
> root：magisk
> 框架：Edxposed
> 问题：ed中勾选框架后重启或软重启支付宝均无法正常运行，也无法查看错误日志。
> 建议：可以搞个夏普的实体机（淘宝一百块）完整root系统不要用虚拟化root，测试框架

手机端如果调试不好，可以尝试使用PC端进行自动偷能量

**Comment by wjcwqc** [comment]
ok

无脸男 <notifications@github.com> 于 2020年3月14日周六 上午12:32写道：
