### ISSUE TITLE
Closed

### ISSUE THREAD

**Issue by LI-XIAOYAO** [WithHades/forestHook#3]
需要打开支付宝或者后台常驻吗

**Comment by WithHades** [comment]
需要。

**Comment by LI-XIAOYAO** [comment]
好像不能自动收了

**Comment by WithHades** [comment]
目前手头不方便看具体情况，应该是不会变的，你可以在xposed日志里看看具体返回了什么信息。。如果信息我没有打印的话，你可以自己下载源码打印一下返回的信息

**Comment by LI-XIAOYAO** [comment]
你看下日志，显示2个好友，去看也是  但是收取是0

2-18 22:17:12.864 I/Xposed  (17778): FriendRankList_send:[{"av":"5","ct":"android","pageSize":20,"startPoint":"61"}]
02-18 22:17:13.087 I/Xposed  (17778): FriendRankList_recv:{"friendRanking":[],"hasMore":false,"myself":{"canCollectEnergy":false,"canCollectLaterTime":-1,"canHelpCollect":false,"collectableBubbleCount":0,"displayName":"","energySummation":0,"forestUser":false,"headPortrait":"","rank":0,"realName":false,"treeAmount":0},"nextStartPoint":"","queryTimestamp":1550499433573,"resultCode":"SUCCESS","resultDesc":"成功","retriable":false,"success":true}
02-18 22:17:13.088 I/Xposed  (17778): 可操作好友共2个
02-18 22:17:13.088 I/Xposed  (17778): rpcCall_CanCollectEnergy_send:[{"version":"20180917"}]
02-18 22:17:13.318 I/Xposed  (17778): rpcCall_CanCollectEnergy_recv:{"bizNo":"2e722c21-7f34-487c-94a8-f891efcfdbb8-1550499433782","bubbles":[],"combineHandlerVOMap":{"eventConfig":{"action":"可点击","background":"https://gw.alipayobjects.com/mdn/social_todo/afts/img/A*wZM8RIUIVNgAAAAAAAAAAABjAwAAAQ/original","btnText":"去浇水","desc":"1月25日-2月4日期间，给福气林浇水，<br/>有机会获得福卡哦","enableFlag":"1","endTime":1550591999000,"eventUrl":"alipays://platformapi/startapp?appId=68687251&nbupdate=synctry&nbversion=0.1.1901172345.51","extInfo":{"guideImg":"https://gw.alipayobjects.com/zos/rmsportal/jEZrChMnBYKpLXuXiSFt.png"},"firstTime":false,"gmtCreate":1542592800000,"gmtModified":1542592800000,"icon":"","id":1546576152,"mainUrl":"alipays://platformapi/startapp?appId=68687266","onlineFlag":"1","resultCode":"SUCCESS","resultDesc":"成功","startTime":1549555199000,"subText":"查看五福活动 >","success":true,"themeType":"Spring2019","themeVersion":"0.4.12","title":"全民浇水 共筑福气林","type":"Spring2019"},"plantTreeCount":{"plantTreeCountDetailVOList":[],"resultCode":"SUCCESS","resultDesc":"成功","success":true}},"indexDressVO":{"dressDetailList":[],"h5VersionForDress":"","showDress":false},"needGuide":false,"nextAction":"Cultivate","now":1550499433781,"properties":{"antfarmEntry":"Y","degradeAntfarmQuery":"N","degradeIndexInvite":"N","degradeSendCustomizedBarrage":"Y","exchangeMode":"Y","lastLogin":"1545177946565","weather":"Y"},"resultCode":"SUCCESS","resultDesc":"成功","retriable":false,"success":true,"totalActivityCertificates":0,"treeEnergy":{"alias":"shijie","allPhases":[{"index":1,"maxPercent":0,"minPercent":0,"needEnergy":0},{"index":2,"maxPercent":0,"minPercent":0,"needEnergy":895},{"index":3,"maxPercent":0,"minPercent":0,"needEnergy":2685},{"index":4,"maxPercent":0,"minPercent":0,"needEnergy":5370},{"index":5,"maxPercent":0,"minPercent":0,"needEnergy":8950},{"index":6,"maxPercent":0,"minPercent":0,"needEnergy":12530},{"index":7,"maxPercent":200,"minPercent":100,"needEnergy":999999999}],"certificateId":"HE170406193913073026584212","currentEnergy":27712,"currentPhase":{"index":6,"maxPercent":0,"minPercent":0,"needEnergy":12530},"distance":999972287,"extInfo":{"dress":{"tree__1":{"dtype":"XC_AN","exTime":1550591999000},"tree__2":{"dtype":"XC_XIN2","exTime":1550591999000},"tree__3":{"dtype":"XC_NUAN","exTime":1550591999000}}},"fullEnergy":999999999,"id":133918,"nextPhase":{"index":7,"maxPercent":200,"minPercent":100,"needEnergy":999999999},"projectId":0,"templateId":2,"treeName":"世界树","type":"COLLECT","userId":"2088212485620370"},"userEnergy":{"canCollectEnergy":false,"canCollectLaterTime":-1,"canHelpCollect":false,"collectableBubbleCount":0,"displayName":"章伟","energySummation":29152,"forestUser":false,"headPortrait":"","realName":true,"treeAmount":0,"userId":"2088212485620370"},"usingUserProps":[]}
02-18 22:17:13.318 I/Xposed  (17778): rpcCall_CanCollectEnergy_send:[{"userId":"2088512743465955","version":"20180917"}]
02-18 22:17:13.678 I/Xposed  (17778): rpcCall_CanCollectEnergy_recv:{"bizNo":"d105ced3-f088-4fe3-908f-889c276f45d6-1550499434048","bubbles":[{"business":{"bigIconDisplayName":"行走","bizType":"xingzou","dayIconUrl":"https://gw.alipayobjects.com/zos/rmsportal/ICaWFQHVAxlfbUdQFjzC.png","id":9,"nightIconUrl":"https://gw.alipayobjects.com/zos/rmsportal/BhLUOcIrKEJwmkmlXxic.png","smallIconDisplayName":"行走"},"canHelpCollect":false,"collectStatus":"INSUFFICIENT","fullEnergy":77,"id":3600631359,"overTime":1550618881000,"produceTime":1550359681000,"remainEnergy":39,"userId":"2088512743465955"},{"business":{"bigIconDisplayName":"线下支付","bizType":"xianxiazhifu","dayIconUrl":"https://zos.alipayobjects.com/rmsportal/yTDRgLNTIRQYhOP.png","id":7,"nightIconUrl":"https://zos.alipayobjects.com/rmsportal/RWtkxNvBYnuZylq.png","smallIconDisplayName":"线下支付"},"canHelpCollect":false,"collectStatus":"INSUFFICIENT","fullEnergy":5,"id":3600631736,"overTime":1550624389000,"produceTime":1550365189000,"remainEnergy":3,"userId":"2088512743465955"},{"business":{"bigIconDisplayName":"共享单车","bizType":"gongxiangdanche","dayIconUrl":"https://gw.alipayobjects.com/zos/rmsportal/bnHTzMaNTAbaPYySUYcw.png","id":15,"nightIconUrl":"https://gw.alipayobjects.com/zos/rmsportal/XsBcemQnWKhiyBAqpzEg.png","smallIconDisplayName":"共享单车"},"canHelpCollect":false,"collectStatus":"INSUFFICIENT","fullEnergy":7,"id":3800236109,"overTime":1550646308000,"produceTime":1550387108000,"remainEnergy":4,"userId":"2088512743465955"},{"business":{"bigIconDisplayName":"线下支付","bizType":"xianxiazhifu","dayIconUrl":"https://zos.alipayobjects.com/rmsportal/yTDRgLNTIRQYhOP.png","id":7,"nightIconUrl":"https://zos.alipayobjects.com/rmsportal/RWtkxNvBYnuZylq.png","smallIconDisplayName":"线下支付"},"canHelpCollect":false,"collectStatus":"INSUFFICIENT","fullEnergy":5,"id":3601705128,"overTime":1550646937000,"produceTime":1550387737000,"remainEnergy":3,"userId":"2088512743465955"},{"business":{"bigIconDisplayName":"行走","bizType":"xingzou","dayIconUrl":"https://gw.alipayobjects.com/zos/rmsportal/ICaWFQHVAxlfbUdQFjzC.png","id":9,"nightIconUrl":"https://gw.alipayobjects.com/zos/rmsportal/BhLUOcIrKEJwmkmlXxic.png","smallIconDisplayName":"行走"},"canHelpCollect":false,"collectStatus":"AVAILABLE","fullEnergy":180,"id":3801742708,"overTime":1550705281000,"produceTime":1550446081000,"remainEnergy":118,"userId":"2088512743465955"},{"business":{"bigIconDisplayName":"线下支付","bizType":"xianxiazhifu","dayIconUrl":"https://zos.alipayobjects.com/rmsportal/yTDRgLNTIRQYhOP.png","id":7,"nightIconUrl":"https://zos.alipayobjects.com/rmsportal/RWtkxNvBYnuZylq.png","smallIconDisplayName":"线下支付"},"canHelpCollect":false,"collectStatus":"INSUFFICIENT","fullEnergy":5,"id":3801742986,"overTime":1550735332000,"produceTime":1550476132000,"remainEnergy":3,"userId":"2088512743465955"}],"combineHandlerVOMap":{"eventConfig":{"action":"可点击","background":"https://gw.alipayobjects.com/mdn/social_todo/afts/img/A*wZM8RIUIVNgAAAAAAAAAAABjAwAAAQ/original","btnText":"去浇水","desc":"1月25日-2月4日期间，给福气林浇水，<br/>有机会获得福卡哦","enableFlag":"1","endTime":1550591999000,"eventUrl":"alipays://platformapi/startapp?appId=68687251&nbupdate=synctry&nbversion=0.1.1901172345.51","extInfo":{"guideImg":"https://gw.alipayobjects.com/zos/rmsportal/jEZrChMnBYKpLXuXiSFt.png"},"firstTime":false,"gmtCreate":1542592800000,"gmtModified":1542592800000,"icon":"","id":1546576152,"mainUrl":"alipays://platformapi/startapp?appId=68687266","onlineFlag":"1","resultCode":"SUCCESS","resultDesc":"成功","startTime":1549555199000,"subText":"查看五福活动 >","success":true,"themeType":"Spring2019","themeVersion":"0.4.12","title":"全民浇水 共筑福气林","type":"Spring2019"},"plantTreeCount":{"plantTreeCountDetailVOList":[{"alias":"shaliu","code":"SP","icon":"https://zos.alipayobjects.com/rmsportal/ZIzByZhVYhwatHcpLaAn.png","name":"沙柳","number":1,"type":"TREE"},{"alias":"shaji","code":"SJ","icon":"https://gw.alipayobjects.com/zos/rmsportal/sBTeIp
02-18 22:17:13.681 I/Xposed  (17778): collectEnergy_send:[{"bubbleIds":[-493224588],"userId":"2088512743465955"}]
02-18 22:17:13.984 I/Xposed  (17778): collectEnergy_recv:{"bubbles":[],"crossPhase":false,"failedBubbleIds":[],"resultCode":"SUCCESS","resultDesc":"成功","retriable":false,"success":true,"treeEnergy":{"alias":"shijie","allPhases":[{"index":1,"maxPercent":0,"minPercent":0,"needEnergy":0},{"index":2,"maxPercent":0,"minPercent":0,"needEnergy":895},{"index":3,"maxPercent":0,"minPercent":0,"needEnergy":2685},{"index":4,"maxPercent":0,"minPercent":0,"needEnergy":5370},{"index":5,"maxPercent":0,"minPercent":0,"needEnergy":8950},{"index":6,"maxPercent":0,"minPercent":0,"needEnergy":12530},{"index":7,"maxPercent":200,"minPercent":100,"needEnergy":999999999}],"certificateId":"HE170406193913073026584212","currentEnergy":27712,"currentPhase":{"index":6,"maxPercent":0,"minPercent":0,"needEnergy":12530},"distance":999972287,"extInfo":{"dress":{"tree__1":{"dtype":"XC_AN","exTime":1550591999000},"tree__2":{"dtype":"XC_XIN2","exTime":1550591999000},"tree__3":{"dtype":"XC_NUAN","exTime":1550591999000}}},"fullEnergy":999999999,"id":133918,"nextPhase":{"index":7,"maxPercent":200,"minPercent":100,"needEnergy":999999999},"projectId":0,"templateId":2,"treeName":"世界树","type":"COLLECT","userId":"2088212485620370"}}
02-18 22:17:13.985 I/Xposed  (17778): rpcCall_CanCollectEnergy_send:[{"userId":"2088612287672889","version":"20180917"}]
02-18 22:17:14.290 I/Xposed  (17778): rpcCall_CanCollectEnergy_recv:{"bizNo":"6b92a67f-cdb0-480b-8085-029d430e3a18-1550499434725","bubbles":[{"business":{"bigIconDisplayName":"线下支付","bizType":"xianxiazhifu","dayIconUrl":"https://zos.alipayobjects.com/rmsportal/yTDRgLNTIRQYhOP.png","id":7,"nightIconUrl":"https://zos.alipayobjects.com/rmsportal/RWtkxNvBYnuZylq.png","smallIconDisplayName":"线下支付"},"canHelpCollect":false,"collectStatus":"AVAILABLE","fullEnergy":5,"id":3802436321,"overTime":1550751830000,"produceTime":1550492630000,"remainEnergy":4,"userId":"2088612287672889"}],"combineHandlerVOMap":{"eventConfig":{"action":"可点击","background":"https://gw.alipayobjects.com/mdn/social_todo/afts/img/A*wZM8RIUIVNgAAAAAAAAAAABjAwAAAQ/original","btnText":"去浇水","desc":"1月25日-2月4日期间，给福气林浇水，<br/>有机会获得福卡哦","enableFlag":"1","endTime":1550591999000,"eventUrl":"alipays://platformapi/startapp?appId=68687251&nbupdate=synctry&nbversion=0.1.1901172345.51","extInfo":{"guideImg":"https://gw.alipayobjects.com/zos/rmsportal/jEZrChMnBYKpLXuXiSFt.png"},"firstTime":false,"gmtCreate":1542592800000,"gmtModified":1542592800000,"icon":"","id":1546576152,"mainUrl":"alipays://platformapi/startapp?appId=68687266","onlineFlag":"1","resultCode":"SUCCESS","resultDesc":"成功","startTime":1549555199000,"subText":"查看五福活动 >","success":true,"themeType":"Spring2019","themeVersion":"0.4.12","title":"全民浇水 共筑福气林","type":"Spring2019"},"plantTreeCount":{"plantTreeCountDetailVOList":[],"resultCode":"SUCCESS","resultDesc":"成功","success":true}},"indexDressVO":{"dressDetailList":[],"h5VersionForDress":"","showDress":false},"needGuide":false,"nextAction":"Friend","now":1550499434725,"properties":{"antfarmEntry":"Y","degradeAntfarmQuery":"N","degradeIndexInvite":"N","degradeSendCustomizedBarrage":"Y","exchangeMode":"Y","lastLogin":"1544663375802","weather":"Y"},"resultCode":"SUCCESS","resultDesc":"成功","retriable":false,"success":true,"totalActivityCertificates":0,"treeEnergy":{"alias":"shijie","allPhases":[{"index":1,"maxPercent":0,"minPercent":0,"needEnergy":0},{"index":2,"maxPercent":0,"minPercent":0,"needEnergy":895},{"index":3,"maxPercent":0,"minPercent":0,"needEnergy":2685},{"index":4,"maxPercent":0,"minPercent":0,"needEnergy":5370},{"index":5,"maxPercent":0,"minPercent":0,"needEnergy":8950},{"index":6,"maxPercent":0,"minPercent":0,"needEnergy":12530},{"index":7,"maxPercent":200,"minPercent":100,"needEnergy":999999999}],"currentEnergy":224,"currentPhase":{"index":1,"maxPercent":0,"minPercent":0,"needEnergy":0},"distance":671,"extInfo":{"dress":{"tree__1":{"dtype":"XC_XING","exTime":1550591999000},"tree__2":{"dtype":"XC_YING","exTime":1550591999000}}},"fullEnergy":999999999,"id":1123941,"nextPhase":{"index":2,"maxPercent":0,"minPercent":0,"needEnergy":895},"projectId":0,"templateId":2,"treeName":"世界树","type":"COLLECT","userId":"2088612287672889"},"userEnergy":{"canCollectEnergy":false,"canCollectLaterTime":-1,"canHelpCollect":false,"collectableBubbleCount":0,"displayName":"*冠林","energySummation":834,"forestUser":false,"headPortrait":"","loginId":"158****0823","realName":false,"treeAmount":0,"userId":"2088612287672889"},"usingUserProps":[]}
02-18 22:17:14.295 I/Xposed  (17778): collectEnergy_send:[{"bubbleIds":[-492530975],"userId":"2088612287672889"}]
02-18 22:17:14.700 I/Xposed  (17778): collectEnergy_recv:{"bubbles":[],"crossPhase":false,"failedBubbleIds":[],"resultCode":"SUCCESS","resultDesc":"成功","retriable":false,"success":true,"treeEnergy":{"alias":"shijie","allPhases":[{"index":1,"maxPercent":0,"minPercent":0,"needEnergy":0},{"index":2,"maxPercent":0,"minPercent":0,"needEnergy":895},{"index":3,"maxPercent":0,"minPercent":0,"needEnergy":2685},{"index":4,"maxPercent":0,"minPercent":0,"needEnergy":5370},{"index":5,"maxPercent":0,"minPercent":0,"needEnergy":8950},{"index":6,"maxPercent":0,"minPercent":0,"needEnergy":12530},{"index":7,"maxPercent":200,"minPercent":100,"needEnergy":999999999}],"certificateId":"HE170406193913073026584212","currentEnergy":27712,"currentPhase":{"index":6,"maxPercent":0,"minPercent":0,"needEnergy":12530},"distance":999972287,"extInfo":{"dress":{"tree__1":{"dtype":"XC_AN","exTime":1550591999000},"tree__2":{"dtype":"XC_XIN2","exTime":1550591999000},"tree__3":{"dtype":"XC_NUAN","exTime":1550591999000}}},"fullEnergy":999999999,"id":133918,"nextPhase":{"index":7,"maxPercent":200,"minPercent":100,"needEnergy":999999999},"projectId":0,"templateId":2,"treeName":"世界树","type":"COLLECT","userId":"2088212485620370"}}
02-18 22:17:14.701 I/Xposed  (17778): 一共收取了0g能量

**Comment by LI-XIAOYAO** [comment]
日志输出的这个好像是id错了 没有编译工具
collectEnergy_send:[{"bubbleIds":[-492530975],"userId":"20886127672889"}]

		"canHelpCollect": false,
		"collectStatus": "AVAILABLE",
		"fullEnergy": 5,
		"id": 3802436321,
		"overTime": 1550751830000,
		"produceTime": 1550492630000,
		"remainEnergy": 4,
		"userId": "20886127672889"
