### ISSUE TITLE
日志

### ISSUE THREAD

**Issue by HandsomeXi** [WithHades/forestHook#8]
您知道这个日志怎么去掉吗？我找了好久没找到，好像是native的log？
[https://i.loli.net/2019/12/14/WDRo74Hd52lQIwj.jpg](url)

**Comment by HandsomeXi** [comment]
https://i.loli.net/2019/12/14/WDRo74Hd52lQIwj.jpg

**Comment by WithHades** [comment]
AbstractJni.java
你可以直接搜索"string="

**Comment by HandsomeXi** [comment]
解决了,thanks!
