### ISSUE TITLE
可以增加一个给好友交税18g,浇水3次的操作吗

### ISSUE THREAD

**Issue by ggxxuser** [WithHades/forestHook#9]
可以增加一个给好友交税18g,浇水3次的操作吗

**Comment by ggxxuser** [comment]
是浇水，打错了，不好意思

**Comment by WithHades** [comment]
emmm浇水的cmd为alipay.antmember.forest.h5.transferEnergy

提交数据为[{"bizNo":"d596c8df-xxxx-43b2-a644-6ec7969c2754-1","targetUser":"208880225839xxxx","transferType":"WATERING","version":"20181217"}]


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ggxxuser"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月26日(星期四) 上午10:48
收件人:&nbsp;"WithHades/forest"<forest@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [WithHades/forest] 可以增加一个给好友交税18g,浇水3次的操作吗 (#9)




是浇水，打错了，不好意思

**Comment by ggxxuser** [comment]
https://github.com/WithHades/forest/issues/9#issuecomment-568954853

> 
> emmm浇水的cmd为alipay.antmember.forest.h5.transferEnergy 提交数据为[{"bizNo":"d596c8df-xxxx-43b2-a644-6ec7969c2754-1","targetUser":"208880225839xxxx","transferType":"WATERING","version":"20181217"}]
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"ggxxuser"<notifications@github.com&gt;; 发送时间:&nbsp;2019年12月26日(星期四) 上午10:48 收件人:&nbsp;"WithHades/forest"<forest@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;Re: [WithHades/forest] 可以增加一个给好友交税18g,浇水3次的操作吗 (#9) 是浇水，打错了，不好意思 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我是纯小白，您方便把浇水的代码封装到APP里面吗？
我有四个小号，每天登陆上去给大号浇水好麻烦。
要是有你这个APP，就方便了。
如果有空的话拜托您更新一下，谢谢您。
